name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run'
        required: true
        type: choice
        options:
          - build
          - build-dev
  push:
    tags:
      - '*'
jobs:  
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.event.inputs.job == 'build' }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  build-dev:

    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'build-dev' }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
