name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run (build, build-dev, deploy-prod, rollback-dev, rollback-prod)'
        required: true
        type: string
        default: 'build' 
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  build-dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
