name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      pipeline:
        description: 'Select custom pipeline to run (build, deploy, etc.)'
        required: true
        default: 'build'
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

