name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      pipeline:
        description: 'Pipeline to run'
        required: true
        type: choice
        options:
          - build
          - build-dev
          - all

    

jobs:  
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.pipeline == 'build' || github.event.inputs.pipeline == 'all' }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  build-dev:

    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.pipeline == 'build-dev' || github.event.inputs.pipeline == 'all' }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
